//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("hub-response", Namespace="", IsNullable=false)]
public partial class hubresponse {
    
    private hubresponseTransactionOutput[] transactionOutputField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TransactionOutput")]
    public hubresponseTransactionOutput[] TransactionOutput {
        get {
            return this.transactionOutputField;
        }
        set {
            this.transactionOutputField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutput {
    
    private hubresponseTransactionOutputCard cardField;
    
    private hubresponseTransactionOutputState stateField;
    
    private hubresponseTransactionOutputAdditionalInformation additionalInformationField;
    
    private hubresponseTransactionOutputChargeslipData[] chargeslipDataField;
    
    private string idField;
    
    /// <remarks/>
    public hubresponseTransactionOutputCard Card {
        get {
            return this.cardField;
        }
        set {
            this.cardField = value;
        }
    }
    
    /// <remarks/>
    public hubresponseTransactionOutputState State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    public hubresponseTransactionOutputAdditionalInformation AdditionalInformation {
        get {
            return this.additionalInformationField;
        }
        set {
            this.additionalInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ChargeslipData")]
    public hubresponseTransactionOutputChargeslipData[] ChargeslipData {
        get {
            return this.chargeslipDataField;
        }
        set {
            this.chargeslipDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputCard {
    
    private bool isManualEntryField;
    
    private string cardNumberField;
    
    private hubresponseTransactionOutputCardExpirationDate expirationDateField;
    
    private string cardholderNameField;
    
    private string issuerNameField;
    
    private string schemeTypeField;
    
    private string parseErrorField;
    
    private hubresponseTransactionOutputCardEMVSpecificData eMVSpecificDataField;
    
    /// <remarks/>
    public bool IsManualEntry {
        get {
            return this.isManualEntryField;
        }
        set {
            this.isManualEntryField = value;
        }
    }
    
    /// <remarks/>
    public string CardNumber {
        get {
            return this.cardNumberField;
        }
        set {
            this.cardNumberField = value;
        }
    }
    
    /// <remarks/>
    public hubresponseTransactionOutputCardExpirationDate ExpirationDate {
        get {
            return this.expirationDateField;
        }
        set {
            this.expirationDateField = value;
        }
    }
    
    /// <remarks/>
    public string CardholderName {
        get {
            return this.cardholderNameField;
        }
        set {
            this.cardholderNameField = value;
        }
    }
    
    /// <remarks/>
    public string IssuerName {
        get {
            return this.issuerNameField;
        }
        set {
            this.issuerNameField = value;
        }
    }
    
    /// <remarks/>
    public string SchemeType {
        get {
            return this.schemeTypeField;
        }
        set {
            this.schemeTypeField = value;
        }
    }
    
    /// <remarks/>
    public string ParseError {
        get {
            return this.parseErrorField;
        }
        set {
            this.parseErrorField = value;
        }
    }
    
    /// <remarks/>
    public hubresponseTransactionOutputCardEMVSpecificData EMVSpecificData {
        get {
            return this.eMVSpecificDataField;
        }
        set {
            this.eMVSpecificDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputCardExpirationDate {
    
    private string mmField;
    
    private string yyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string MM {
        get {
            return this.mmField;
        }
        set {
            this.mmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string YY {
        get {
            return this.yyField;
        }
        set {
            this.yyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputCardEMVSpecificData {
    
    private bool isOnlineField;
    
    private bool isRequestField;
    
    private bool isApprovedField;
    
    private string aIDField;
    
    private string field55DataField;
    
    private string tIDField;
    
    private string invoiceNumberField;
    
    /// <remarks/>
    public bool IsOnline {
        get {
            return this.isOnlineField;
        }
        set {
            this.isOnlineField = value;
        }
    }
    
    /// <remarks/>
    public bool IsRequest {
        get {
            return this.isRequestField;
        }
        set {
            this.isRequestField = value;
        }
    }
    
    /// <remarks/>
    public bool IsApproved {
        get {
            return this.isApprovedField;
        }
        set {
            this.isApprovedField = value;
        }
    }
    
    /// <remarks/>
    public string AID {
        get {
            return this.aIDField;
        }
        set {
            this.aIDField = value;
        }
    }
    
    /// <remarks/>
    public string Field55Data {
        get {
            return this.field55DataField;
        }
        set {
            this.field55DataField = value;
        }
    }
    

    public string TID {
        get {
            return this.tIDField;
        }
        set {
            this.tIDField = value;
        }
    }
    

    public string InvoiceNumber {
        get {
            return this.invoiceNumberField;
        }
        set {
            this.invoiceNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputState {
    
    private hubresponseTransactionOutputStateSelectedAcquirer selectedAcquirerField;
    
    private string terminalIDField;
    
    private hubresponseTransactionOutputStateMerchant merchantField;
    
    private string invoiceNumberField;
    
    private string batchNumberField;
    
    private string acquirerNameField;
    
    private string transactionTimeField;
    
    private hubresponseTransactionOutputStateHostResponse hostResponseField;
    
    private string statusCodeField;
    
    private string statusMessageField;
    
    private hubresponseTransactionOutputStateLoyaltyResponse loyaltyResponseField;
    
    private string trackingNumberField;

    
    /// <remarks/>
    public hubresponseTransactionOutputStateSelectedAcquirer SelectedAcquirer {
        get {
            return this.selectedAcquirerField;
        }
        set {
            this.selectedAcquirerField = value;
        }
    }
    
    /// <remarks/>
    public string TerminalID {
        get {
            return this.terminalIDField;
        }
        set {
            this.terminalIDField = value;
        }
    }
    
    /// <remarks/>
    public hubresponseTransactionOutputStateMerchant Merchant {
        get {
            return this.merchantField;
        }
        set {
            this.merchantField = value;
        }
    }
    
    /// <remarks/>
    public string InvoiceNumber {
        get {
            return this.invoiceNumberField;
        }
        set {
            this.invoiceNumberField = value;
        }
    }
    
   
    

    public string BatchNumber {
        get {
            return this.batchNumberField;
        }
        set {
            this.batchNumberField = value;
        }
    }
    
    /// <remarks/>
    public string AcquirerName {
        get {
            return this.acquirerNameField;
        }
        set {
            this.acquirerNameField = value;
        }
    }
    
    /// <remarks/>
    public string TransactionTime {
        get {
            return this.transactionTimeField;
        }
        set {
            this.transactionTimeField = value;
        }
    }
    
    
    /// <remarks/>
    public hubresponseTransactionOutputStateHostResponse HostResponse {
        get {
            return this.hostResponseField;
        }
        set {
            this.hostResponseField = value;
        }
    }
    
   
    public string StatusCode {
        get {
            return this.statusCodeField;
        }
        set {
            this.statusCodeField = value;
        }
    }
    
    /// <remarks/>
    public string StatusMessage {
        get {
            return this.statusMessageField;
        }
        set {
            this.statusMessageField = value;
        }
    }
    
    /// <remarks/>
    public hubresponseTransactionOutputStateLoyaltyResponse LoyaltyResponse {
        get {
            return this.loyaltyResponseField;
        }
        set {
            this.loyaltyResponseField = value;
        }
    }
    
    /// <remarks/>
    public string TrackingNumber {
        get {
            return this.trackingNumberField;
        }
        set {
            this.trackingNumberField = value;
        }
    }
    
    
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputStateSelectedAcquirer {
    
    private string idField;
    
    private string nameField;
    
    private string discountRateField;
    
    private string statusField;
    
    private string acquirerWorkingKeyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string DiscountRate {
        get {
            return this.discountRateField;
        }
        set {
            this.discountRateField = value;
        }
    }
     
    
    /// <remarks/>
    public string Status {
        get {
            return this.statusField;
        }
        set {
            this.statusField = value;
        }
    }
    
    /// <remarks/>
    public string AcquirerWorkingKey {
        get {
            return this.acquirerWorkingKeyField;
        }
        set {
            this.acquirerWorkingKeyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputStateMerchant {
    
    private string idField;
    
    private string nameField;
    
    private string addressField;
    
    private string cityField;
    
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputStateHostResponse {
    
    private string responseCodeField;
    
    private string responseMessageField;
    
    private string approvalCodeField;
    
    private bool approvalCodeFieldSpecified;
    
    private string retrievalReferenceNumberField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string ResponseCode {
        get {
            return this.responseCodeField;
        }
        set {
            this.responseCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ResponseMessage {
        get {
            return this.responseMessageField;
        }
        set {
            this.responseMessageField = value;
        }
    }
    
    /// <remarks/>
    public string ApprovalCode {
        get {
            return this.approvalCodeField;
        }
        set {
            this.approvalCodeField = value;
        }
    }
    
    
    /// <remarks/>
    public string RetrievalReferenceNumber {
        get {
            return this.retrievalReferenceNumberField;
        }
        set {
            this.retrievalReferenceNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputStateLoyaltyResponse {
    
    private long awardedPointsField;
    
    private bool awardedPointsFieldSpecified;
    
    private string message1Field;
    
    private string message2Field;
    
    private string logoIDField;
    
    /// <remarks/>
    public long AwardedPoints {
        get {
            return this.awardedPointsField;
        }
        set {
            this.awardedPointsField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AwardedPointsSpecified {
        get {
            return this.awardedPointsFieldSpecified;
        }
        set {
            this.awardedPointsFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Message1 {
        get {
            return this.message1Field;
        }
        set {
            this.message1Field = value;
        }
    }
    
    /// <remarks/>
    public string Message2 {
        get {
            return this.message2Field;
        }
        set {
            this.message2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string LogoID {
        get {
            return this.logoIDField;
        }
        set {
            this.logoIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputAdditionalInformation {
    
    private hubresponseTransactionOutputAdditionalInformationAddlInfoField[] addlInfoFieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddlInfoField")]
    public hubresponseTransactionOutputAdditionalInformationAddlInfoField[] AddlInfoField {
        get {
            return this.addlInfoFieldField;
        }
        set {
            this.addlInfoFieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputAdditionalInformationAddlInfoField {
    
    private string idField;
    
    private string valueField;
    
    private string typeField;
    
    private byte[] hexValueField;
    
    private byte binaryValueField;
    
    private bool binaryValueFieldSpecified;
    
    private string integerValueField;
    
    private long longValueField;
    
    private bool longValueFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
    public byte[] HexValue {
        get {
            return this.hexValueField;
        }
        set {
            this.hexValueField = value;
        }
    }
    
    /// <remarks/>
    public byte BinaryValue {
        get {
            return this.binaryValueField;
        }
        set {
            this.binaryValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BinaryValueSpecified {
        get {
            return this.binaryValueFieldSpecified;
        }
        set {
            this.binaryValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string IntegerValue {
        get {
            return this.integerValueField;
        }
        set {
            this.integerValueField = value;
        }
    }
    
    /// <remarks/>
    public long LongValue {
        get {
            return this.longValueField;
        }
        set {
            this.longValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LongValueSpecified {
        get {
            return this.longValueFieldSpecified;
        }
        set {
            this.longValueFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputChargeslipData {
    
    private hubresponseTransactionOutputChargeslipDataReceipt[] receiptField;
    
    private string printerWidthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Receipt")]
    public hubresponseTransactionOutputChargeslipDataReceipt[] Receipt {
        get {
            return this.receiptField;
        }
        set {
            this.receiptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string printerWidth {
        get {
            return this.printerWidthField;
        }
        set {
            this.printerWidthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputChargeslipDataReceipt {
    
    private hubresponseTransactionOutputChargeslipDataReceiptPrintLine[] printLineField;
    
    private bool isCustomerCopyField;
    
    private bool isCustomerCopyFieldSpecified;
    
    private long lineCountField;
    
    private bool lineCountFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PrintLine")]
    public hubresponseTransactionOutputChargeslipDataReceiptPrintLine[] PrintLine {
        get {
            return this.printLineField;
        }
        set {
            this.printLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isCustomerCopy {
        get {
            return this.isCustomerCopyField;
        }
        set {
            this.isCustomerCopyField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isCustomerCopySpecified {
        get {
            return this.isCustomerCopyFieldSpecified;
        }
        set {
            this.isCustomerCopyFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long lineCount {
        get {
            return this.lineCountField;
        }
        set {
            this.lineCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lineCountSpecified {
        get {
            return this.lineCountFieldSpecified;
        }
        set {
            this.lineCountFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class hubresponseTransactionOutputChargeslipDataReceiptPrintLine {
    
    private long lineNumberField;
    
    private bool lineNumberFieldSpecified;
    
    private string bitmapIDField;
    
    private bool isCenteredField;
    
    private bool isCenteredFieldSpecified;
    
    private bool isBoldField;
    
    private bool isBoldFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long lineNumber {
        get {
            return this.lineNumberField;
        }
        set {
            this.lineNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lineNumberSpecified {
        get {
            return this.lineNumberFieldSpecified;
        }
        set {
            this.lineNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bitmapID {
        get {
            return this.bitmapIDField;
        }
        set {
            this.bitmapIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isCentered {
        get {
            return this.isCenteredField;
        }
        set {
            this.isCenteredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isCenteredSpecified {
        get {
            return this.isCenteredFieldSpecified;
        }
        set {
            this.isCenteredFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isBold {
        get {
            return this.isBoldField;
        }
        set {
            this.isBoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isBoldSpecified {
        get {
            return this.isBoldFieldSpecified;
        }
        set {
            this.isBoldFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}
