//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("purchase-request", Namespace="", IsNullable=false)]
public partial class purchaserequest {
    
    private purchaserequestTransactionInput[] transactionInputField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TransactionInput")]
    public purchaserequestTransactionInput[] TransactionInput {
        get {
            return this.transactionInputField;
        }
        set {
            this.transactionInputField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaserequestTransactionInput {
    
    private purchaserequestTransactionInputCard cardField;
    
    private purchaserequestTransactionInputAmount amountField;
    
    private purchaserequestTransactionInputPOS pOSField;
    
    private purchaserequestTransactionInputAdditionalInformation additionalInformationField;
    
    private string idField;
    
    /// <remarks/>
    public purchaserequestTransactionInputCard Card {
        get {
            return this.cardField;
        }
        set {
            this.cardField = value;
        }
    }
    
    /// <remarks/>
    public purchaserequestTransactionInputAmount Amount {
        get {
            return this.amountField;
        }
        set {
            this.amountField = value;
        }
    }
    
    /// <remarks/>
    public purchaserequestTransactionInputPOS POS {
        get {
            return this.pOSField;
        }
        set {
            this.pOSField = value;
        }
    }
    
    /// <remarks/>
    public purchaserequestTransactionInputAdditionalInformation AdditionalInformation {
        get {
            return this.additionalInformationField;
        }
        set {
            this.additionalInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="ID")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaserequestTransactionInputCard {
    
    private bool isManualEntryField;
    
    private string cardNumberField;
    
    private purchaserequestTransactionInputCardExpirationDate expirationDateField;
    
    private bool isFallbackEntryField;
    
    private bool isFallbackEntryFieldSpecified;
    
    private string track1Field;
    
    private string track2Field;
    
    private purchaserequestTransactionInputCardEMVSpecificData eMVSpecificDataField;
    
    public purchaserequestTransactionInputCard() {
        this.isManualEntryField = false;
    }
    
    /// <remarks/>
    public bool IsManualEntry {
        get {
            return this.isManualEntryField;
        }
        set {
            this.isManualEntryField = value;
        }
    }
    
    /// <remarks/>
    public string CardNumber {
        get {
            return this.cardNumberField;
        }
        set {
            this.cardNumberField = value;
        }
    }
    
    /// <remarks/>
    public purchaserequestTransactionInputCardExpirationDate ExpirationDate {
        get {
            return this.expirationDateField;
        }
        set {
            this.expirationDateField = value;
        }
    }
    
    /// <remarks/>
    public bool IsFallbackEntry {
        get {
            return this.isFallbackEntryField;
        }
        set {
            this.isFallbackEntryField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool IsFallbackEntrySpecified {
        get {
            return this.isFallbackEntryFieldSpecified;
        }
        set {
            this.isFallbackEntryFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string Track1 {
        get {
            return this.track1Field;
        }
        set {
            this.track1Field = value;
        }
    }
    
    /// <remarks/>
    public string Track2 {
        get {
            return this.track2Field;
        }
        set {
            this.track2Field = value;
        }
    }
    
    /// <remarks/>
    public purchaserequestTransactionInputCardEMVSpecificData EMVSpecificData {
        get {
            return this.eMVSpecificDataField;
        }
        set {
            this.eMVSpecificDataField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaserequestTransactionInputCardExpirationDate {
    
    private string mmField;
    
    private string yyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string MM {
        get {
            return this.mmField;
        }
        set {
            this.mmField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string YY {
        get {
            return this.yyField;
        }
        set {
            this.yyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaserequestTransactionInputCardEMVSpecificData {
    
    private bool isOnlineField;
    
    private bool isRequestField;
    
    private bool isApprovedField;
    
    private string aIDField;
    
    private string field55DataField;
    
    private string tIDField;
    
    private string invoiceNumberField;
    
    /// <remarks/>
    public bool IsOnline {
        get {
            return this.isOnlineField;
        }
        set {
            this.isOnlineField = value;
        }
    }
    
    /// <remarks/>
    public bool IsRequest {
        get {
            return this.isRequestField;
        }
        set {
            this.isRequestField = value;
        }
    }
    
    /// <remarks/>
    public bool IsApproved {
        get {
            return this.isApprovedField;
        }
        set {
            this.isApprovedField = value;
        }
    }
    
    /// <remarks/>
    public string AID {
        get {
            return this.aIDField;
        }
        set {
            this.aIDField = value;
        }
    }
    
    /// <remarks/>
    public string Field55Data {
        get {
            return this.field55DataField;
        }
        set {
            this.field55DataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TID {
        get {
            return this.tIDField;
        }
        set {
            this.tIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string InvoiceNumber {
        get {
            return this.invoiceNumberField;
        }
        set {
            this.invoiceNumberField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaserequestTransactionInputAmount {
    
    private long baseAmountField;
    
    private long additionalAmountField;
    
    private bool additionalAmountFieldSpecified;
    
    private string currencyCodeField;
    
    /// <remarks/>
    public long BaseAmount {
        get {
            return this.baseAmountField;
        }
        set {
            this.baseAmountField = value;
        }
    }
    
    /// <remarks/>
    public long AdditionalAmount {
        get {
            return this.additionalAmountField;
        }
        set {
            this.additionalAmountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool AdditionalAmountSpecified {
        get {
            return this.additionalAmountFieldSpecified;
        }
        set {
            this.additionalAmountFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public string CurrencyCode {
        get {
            return this.currencyCodeField;
        }
        set {
            this.currencyCodeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaserequestTransactionInputPOS {
    
    private string pOSReferenceNumberField;
    
    private string transactionTimeField;
    
    private purchaserequestTransactionInputPOSProduct[] productField;
    
    private purchaserequestTransactionInputPOSUser userField;
    
    private string trackingNumberField;
    
    private string customerIDField;
    
    /// <remarks/>
    public string POSReferenceNumber {
        get {
            return this.pOSReferenceNumberField;
        }
        set {
            this.pOSReferenceNumberField = value;
        }
    }
    
    /// <remarks/>
    public string TransactionTime {
        get {
            return this.transactionTimeField;
        }
        set {
            this.transactionTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Product")]
    public purchaserequestTransactionInputPOSProduct[] Product {
        get {
            return this.productField;
        }
        set {
            this.productField = value;
        }
    }
    
    /// <remarks/>
    public purchaserequestTransactionInputPOSUser User {
        get {
            return this.userField;
        }
        set {
            this.userField = value;
        }
    }
    
    /// <remarks/>
    public string TrackingNumber {
        get {
            return this.trackingNumberField;
        }
        set {
            this.trackingNumberField = value;
        }
    }
    
    
    
    /// <remarks/>
    public string CustomerID {
        get {
            return this.customerIDField;
        }
        set {
            this.customerIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaserequestTransactionInputPOSProduct {
    
    private string codeField;
    
    private string nameField;
    
    private string descriptionField;
    
    private string categoryField;
    
    private long quantityField;
    
    private bool quantityFieldSpecified;
    
    private long unitPriceField;
    
    private bool unitPriceFieldSpecified;
    
    /// <remarks/>
    public string Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    public string Description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
    
    /// <remarks/>
    public string Category {
        get {
            return this.categoryField;
        }
        set {
            this.categoryField = value;
        }
    }
    
    /// <remarks/>
    public long Quantity {
        get {
            return this.quantityField;
        }
        set {
            this.quantityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool QuantitySpecified {
        get {
            return this.quantityFieldSpecified;
        }
        set {
            this.quantityFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public long UnitPrice {
        get {
            return this.unitPriceField;
        }
        set {
            this.unitPriceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool UnitPriceSpecified {
        get {
            return this.unitPriceFieldSpecified;
        }
        set {
            this.unitPriceFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaserequestTransactionInputPOSUser {
    
    private string idField;
    
    private string nameField;
    
    /// <remarks/>
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaserequestTransactionInputAdditionalInformation {
    
    private purchaserequestTransactionInputAdditionalInformationAddlInfoField[] addlInfoFieldField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AddlInfoField")]
    public purchaserequestTransactionInputAdditionalInformationAddlInfoField[] AddlInfoField {
        get {
            return this.addlInfoFieldField;
        }
        set {
            this.addlInfoFieldField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class purchaserequestTransactionInputAdditionalInformationAddlInfoField {
    
    private string idField;
    
    private string valueField;
    
    private long lengthField;
    
    private string typeField;
    
    private byte[] hexValueField;
    
    private byte binaryValueField;
    
    private bool binaryValueFieldSpecified;
    
    private string integerValueField;
    
    private long longValueField;
    
    private bool longValueFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    public long Length {
        get {
            return this.lengthField;
        }
        set {
            this.lengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string Type {
        get {
            return this.typeField;
        }
        set {
            this.typeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="hexBinary")]
    public byte[] HexValue {
        get {
            return this.hexValueField;
        }
        set {
            this.hexValueField = value;
        }
    }
    
    /// <remarks/>
    public byte BinaryValue {
        get {
            return this.binaryValueField;
        }
        set {
            this.binaryValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool BinaryValueSpecified {
        get {
            return this.binaryValueFieldSpecified;
        }
        set {
            this.binaryValueFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string IntegerValue {
        get {
            return this.integerValueField;
        }
        set {
            this.integerValueField = value;
        }
    }
    
    /// <remarks/>
    public long LongValue {
        get {
            return this.longValueField;
        }
        set {
            this.longValueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool LongValueSpecified {
        get {
            return this.longValueFieldSpecified;
        }
        set {
            this.longValueFieldSpecified = value;
        }
    }
}
