//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3615
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=2.0.50727.3038.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute("Settlement-Response", Namespace="", IsNullable=false)]
public partial class SettlementResponse {
    
    private SettlementResponseTransactionOutput transactionOutputField;
    
    /// <remarks/>
    public SettlementResponseTransactionOutput TransactionOutput {
        get {
            return this.transactionOutputField;
        }
        set {
            this.transactionOutputField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SettlementResponseTransactionOutput {
    
    private SettlementResponseTransactionOutputBank[] acquirerField;
    
    private SettlementResponseTransactionOutputState stateField;
    
    private SettlementResponseTransactionOutputAddlInfoField[] additionalInformationField;
    
    private string idField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("Bank", IsNullable=false)]
    public SettlementResponseTransactionOutputBank[] Acquirer {
        get {
            return this.acquirerField;
        }
        set {
            this.acquirerField = value;
        }
    }
    
    /// <remarks/>
    public SettlementResponseTransactionOutputState State {
        get {
            return this.stateField;
        }
        set {
            this.stateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AddlInfoField", IsNullable=false)]
    public SettlementResponseTransactionOutputAddlInfoField[] AdditionalInformation {
        get {
            return this.additionalInformationField;
        }
        set {
            this.additionalInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="IDREF")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SettlementResponseTransactionOutputBank {
    
    private SettlementResponseTransactionOutputBankTerminal[] terminalField;
    
    private string nameField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Terminal")]
    public SettlementResponseTransactionOutputBankTerminal[] Terminal {
        get {
            return this.terminalField;
        }
        set {
            this.terminalField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SettlementResponseTransactionOutputBankTerminal {
    
    private string tIDField;
    
    private System.DateTime transactionTimeField;
    
    private bool transactionTimeFieldSpecified;
    
    private SettlementResponseTransactionOutputBankTerminalTerminalState terminalStateField;
    
    private SettlementResponseTransactionOutputBankTerminalHostResponse hostResponseField;
    
    private SettlementResponseTransactionOutputBankTerminalMerchant merchantField;
    
    private string[] batchNumberField;
    
    private SettlementResponseTransactionOutputBankTerminalAuditReportData auditReportDataField;
    
    private SettlementResponseTransactionOutputBankTerminalAddlInfField[] additionalInfoForTIDField;
    
    /// <remarks/>
    public string TID {
        get {
            return this.tIDField;
        }
        set {
            this.tIDField = value;
        }
    }
    
    /// <remarks/>
    public System.DateTime TransactionTime {
        get {
            return this.transactionTimeField;
        }
        set {
            this.transactionTimeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool TransactionTimeSpecified {
        get {
            return this.transactionTimeFieldSpecified;
        }
        set {
            this.transactionTimeFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    public SettlementResponseTransactionOutputBankTerminalTerminalState TerminalState {
        get {
            return this.terminalStateField;
        }
        set {
            this.terminalStateField = value;
        }
    }
    
    /// <remarks/>
    public SettlementResponseTransactionOutputBankTerminalHostResponse HostResponse {
        get {
            return this.hostResponseField;
        }
        set {
            this.hostResponseField = value;
        }
    }
    
    /// <remarks/>
    public SettlementResponseTransactionOutputBankTerminalMerchant Merchant {
        get {
            return this.merchantField;
        }
        set {
            this.merchantField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BatchNumber", DataType="integer")]
    public string[] BatchNumber {
        get {
            return this.batchNumberField;
        }
        set {
            this.batchNumberField = value;
        }
    }
    
    /// <remarks/>
    public SettlementResponseTransactionOutputBankTerminalAuditReportData AuditReportData {
        get {
            return this.auditReportDataField;
        }
        set {
            this.auditReportDataField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlArrayItemAttribute("AddlInfField", IsNullable=false)]
    public SettlementResponseTransactionOutputBankTerminalAddlInfField[] AdditionalInfoForTID {
        get {
            return this.additionalInfoForTIDField;
        }
        set {
            this.additionalInfoForTIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SettlementResponseTransactionOutputBankTerminalTerminalState {
    
    private string terminalStatusCodeField;
    
    private string terminalStatusMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string TerminalStatusCode {
        get {
            return this.terminalStatusCodeField;
        }
        set {
            this.terminalStatusCodeField = value;
        }
    }
    
    /// <remarks/>
    public string TerminalStatusMessage {
        get {
            return this.terminalStatusMessageField;
        }
        set {
            this.terminalStatusMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SettlementResponseTransactionOutputBankTerminalHostResponse {
    
    private string responseCodeField;
    
    private string responseMessageField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string ResponseCode {
        get {
            return this.responseCodeField;
        }
        set {
            this.responseCodeField = value;
        }
    }
    
    /// <remarks/>
    public string ResponseMessage {
        get {
            return this.responseMessageField;
        }
        set {
            this.responseMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SettlementResponseTransactionOutputBankTerminalMerchant {
    
    private string mIDField;
    
    private string merchantNameField;
    
    private string addressField;
    
    private string cityField;
    
    /// <remarks/>
    public string MID {
        get {
            return this.mIDField;
        }
        set {
            this.mIDField = value;
        }
    }
    
    /// <remarks/>
    public string MerchantName {
        get {
            return this.merchantNameField;
        }
        set {
            this.merchantNameField = value;
        }
    }
    
    /// <remarks/>
    public string Address {
        get {
            return this.addressField;
        }
        set {
            this.addressField = value;
        }
    }
    
    /// <remarks/>
    public string City {
        get {
            return this.cityField;
        }
        set {
            this.cityField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SettlementResponseTransactionOutputBankTerminalAuditReportData {
    
    private SettlementResponseTransactionOutputBankTerminalAuditReportDataReceipt[] receiptField;
    
    private string printerWidthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Receipt")]
    public SettlementResponseTransactionOutputBankTerminalAuditReportDataReceipt[] Receipt {
        get {
            return this.receiptField;
        }
        set {
            this.receiptField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute(DataType="integer")]
    public string printerWidth {
        get {
            return this.printerWidthField;
        }
        set {
            this.printerWidthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SettlementResponseTransactionOutputBankTerminalAuditReportDataReceipt {
    
    private SettlementResponseTransactionOutputBankTerminalAuditReportDataReceiptPrintLine[] printLineField;
    
    private long lineCountField;
    
    private bool lineCountFieldSpecified;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("PrintLine")]
    public SettlementResponseTransactionOutputBankTerminalAuditReportDataReceiptPrintLine[] PrintLine {
        get {
            return this.printLineField;
        }
        set {
            this.printLineField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long lineCount {
        get {
            return this.lineCountField;
        }
        set {
            this.lineCountField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lineCountSpecified {
        get {
            return this.lineCountFieldSpecified;
        }
        set {
            this.lineCountFieldSpecified = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SettlementResponseTransactionOutputBankTerminalAuditReportDataReceiptPrintLine {
    
    private long lineNumberField;
    
    private bool lineNumberFieldSpecified;
    
    private string bitmapIDField;
    
    private bool isCenteredField;
    
    private bool isCenteredFieldSpecified;
    
    private bool isBoldField;
    
    private bool isBoldFieldSpecified;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public long lineNumber {
        get {
            return this.lineNumberField;
        }
        set {
            this.lineNumberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool lineNumberSpecified {
        get {
            return this.lineNumberFieldSpecified;
        }
        set {
            this.lineNumberFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string bitmapID {
        get {
            return this.bitmapIDField;
        }
        set {
            this.bitmapIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isCentered {
        get {
            return this.isCenteredField;
        }
        set {
            this.isCenteredField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isCenteredSpecified {
        get {
            return this.isCenteredFieldSpecified;
        }
        set {
            this.isCenteredFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public bool isBold {
        get {
            return this.isBoldField;
        }
        set {
            this.isBoldField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIgnoreAttribute()]
    public bool isBoldSpecified {
        get {
            return this.isBoldFieldSpecified;
        }
        set {
            this.isBoldFieldSpecified = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SettlementResponseTransactionOutputBankTerminalAddlInfField {
    
    private string idField;
    
    private string labelField;
    
    private bool isNumericField;
    
    private string minLengthField;
    
    private string maxLengthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public bool IsNumeric {
        get {
            return this.isNumericField;
        }
        set {
            this.isNumericField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string MinLength {
        get {
            return this.minLengthField;
        }
        set {
            this.minLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string MaxLength {
        get {
            return this.maxLengthField;
        }
        set {
            this.maxLengthField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SettlementResponseTransactionOutputState {
    
    private string statusCodeField;
    
    private string statusMessageField;
    
    private string  trackingNumberField;
    

    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string StatusCode {
        get {
            return this.statusCodeField;
        }
        set {
            this.statusCodeField = value;
        }
    }
    
    /// <remarks/>
    public string StatusMessage {
        get {
            return this.statusMessageField;
        }
        set {
            this.statusMessageField = value;
        }
    }
    
    /// <remarks/>
    public string TrackingNumber {
        get {
            return this.trackingNumberField;
        }
        set {
            this.trackingNumberField = value;
        }
    }
    
   
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "2.0.50727.3038")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class SettlementResponseTransactionOutputAddlInfoField {
    
    private string idField;
    
    private string labelField;
    
    private bool isNumericField;
    
    private string minLengthField;
    
    private string maxLengthField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public string Label {
        get {
            return this.labelField;
        }
        set {
            this.labelField = value;
        }
    }
    
    /// <remarks/>
    public bool IsNumeric {
        get {
            return this.isNumericField;
        }
        set {
            this.isNumericField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string MinLength {
        get {
            return this.minLengthField;
        }
        set {
            this.minLengthField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
    public string MaxLength {
        get {
            return this.maxLengthField;
        }
        set {
            this.maxLengthField = value;
        }
    }
}
